apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: southamerica-east1-docker.pkg.dev/san-valen-commerce/san-valen-registry/payments-ms
        name: payments-ms
        env:
        - name: PORT
          value: "3003"
        - name: STRIPE_SUCCESS_URL
          value: "http://localhost:3003/payments/success"
        - name: STRIPE_CANCEL_URL
          value: "http://localhost:3003/payments/cancel"
        - name: NATS_SERVERS
          value: "nats://nats-server:4222"
        - name: STRIPE_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-ms-secrets
              key: STRIPE_SECRET
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-ms-secrets
              key: STRIPE_WEBHOOK_SECRET
        resources: {}
status: {}
